config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'flats#index'

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guets)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<section class="container">
  <div>
    <h1>All our Flats (<%= @flats.count %>)</h1>

    <div class="row gap-4">
      <% @flats.each do |flat| %>
        <div class="card col-md-3 shadow p-0">
          <div class="card-body bg-light">
            <h3 class="card-title"><%= flat.name.capitalize %></h3>
            <p class=""><%= flat.address.capitalize %></p>
            <div class="d-flex">
              <i class="fa-solid fa-user-group mt-1 me-2"></i><p class="me-3"><%= flat.number_of_guests %></p>
              <i class="fa-solid fa-euro-sign mt-1 me-2"></i><p class="me-3"><%= flat.price_per_night %></p>
            </div>

          </div>
          <div class="p-3">
            <%= link_to 'More info', flat_path(flat.id), class: 'text-decoration-none' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</section>

app/views/flats/new.html.erb
<section class="container">
  <div class="col-md-6 bg-light mx-auto my-3 p-3">
    <H1>Add a new flat</H1>

    <%= simple_form_for(@flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :number_of_guests %>
    <%= f.input :price_per_night %>
    <%= f.button :submit, class: 'btn btn-primary me-2' %>
    <%= link_to 'Cancel', flats_path, class: 'btn btn-danger' %>

    <% end %>

  </div>
</section>

app/views/flats/show.html.erb
<div style="background-image: url('https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200'); height: 350px !important;"></div>
  <div class="container">

  <div class="row mb-3">
    <div class="col-md-8">
        <div class="p-3 bg-light mb-3 shadow rounded" style="margin-top: -60px;" >
          <h1><%= @flat.name.capitalize %></h1>
          <p class="fs-6"><%= @flat.address %></p>
        </div>
        <div class="p-3 bg-light mt-3 shadow rounded" style="margin-top: -60px;" >
          <h3>A bit more about this</h3>
          <p style="font-size: 14px;"><%= @flat.description %></p>
          <div style="background-image: url(/assets/map.jpg); height: 300px; background-size: cover;"></div>
        </div>
    </div>
    <div class="col-md-4">
      <div class="p-3 bg-light mb-3 shadow rounded" style="margin-top: -60px;" >
        <h6>Book this place!</h6>
        <form action="">
          <div class="input-group">
            <span class="input-group-text" id="start-date-label">From:</span>
            <input type="text" class="form-control" placeholder="01/08/2024" aria-label="start-date" aria-describedby="start-date-label">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-text" id="end-date-label">To:</span>
            <input type="text" class="form-control" placeholder="02/08/2024" aria-label="end-date" aria-describedby="start-date-label">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>

      <div class="p-3 bg-light mt-3 shadow rounded" style="margin-top: -60px;" >
        <h3>Details</h3>
        <div class="d-flex">
          <p class="me-4"><%= @flat.number_of_guests %> people</p>
          <p><%= @flat.price_per_night %>€</p>
        </div>
      </div>

      <div class="p-3 bg-light mt-3 shadow rounded" style="margin-top: -60px;" >
        <div class="d-flex me-auto">
          <h6>Share</h6>
          <div class="ms-auto">
            <i class="fa-brands fa-facebook"></i>
            <i class="fa-brands fa-twitter"></i>
            <i class="fa-brands fa-pinterest"></i>
          </div>

        </div>
      </div>

    </div>
  </div>

    <%= link_to 'Back', flats_path %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="px-5 py-3 container-fluid bg-light">
      <a class="navbar-brand text-dark" href="/">Simple Airbnb</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarScroll">
        <div class="d-flex ms-auto">
          <form class="d-flex me-2" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
          <%= link_to 'Add flat', new_flat_path, class: 'btn btn-outline-primary' %>
        </div>
      </div>
    </div>
  </nav>


    <%= yield %>
  </body>
</html>